import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from '../../Common/utils/scale'; // adjust path if needed

const styles = StyleSheet.create({
  container: {
    paddingBottom: verticalScale(20),
    backgroundColor: '#f0f4f8',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: verticalScale(16),
    paddingHorizontal: moderateScale(16),
    justifyContent: 'space-between',
    elevation: 5,
    borderRadius: verticalScale(16),
  },
  dateText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: scale(13),
  },
  shiftButton: {
    backgroundColor: '#007ACC',
    paddingHorizontal: scale(48),
    paddingVertical: verticalScale(6),
    borderRadius: verticalScale(10),
    elevation: 2,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: scale(13),
  },
  picker: {
    backgroundColor: '#fff',
    borderColor: '#ccc',
    borderRadius: moderateScale(10),
    width: scale(150),
    padding: verticalScale(6),
  },
  chartSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    margin: moderateScale(16),
    flexWrap: 'wrap',
  },
  progressContainer: {
    alignItems: 'center',
    marginBottom: verticalScale(20),
  },
  chartPercentage: {
    fontSize: scale(18),
    fontWeight: 'bold',
    color: '#004080',
  },
  chartTitle: {
    marginTop: verticalScale(6),
    fontWeight: '600',
    fontSize: scale(14),
    color: '#333',
  },
  headerBox: {
    backgroundColor: '#007ACC',
    color: 'white',
    padding: moderateScale(10),
    borderRadius: moderateScale(10),
    fontWeight: 'bold',
    minWidth: scale(60),
    textAlign: 'center',
  },
  assignBtn: {
    backgroundColor: '#28a745',
    paddingVertical: verticalScale(6),
    paddingHorizontal: moderateScale(8),
    borderRadius: verticalScale(10),
    justifyContent: 'center',
    alignSelf: 'center',
    elevation: 3,
    maxWidth: scale(150),
  },
  detailsBtn: {
    backgroundColor: 'black',
    color: 'white',
    paddingVertical: verticalScale(6),
    paddingHorizontal: scale(36),
    borderRadius: verticalScale(10),
    alignSelf: 'center',
    elevation: 3,
    marginLeft: scale(40),
  },
  section: {
    backgroundColor: '#ffffff',
    padding: moderateScale(15),
    marginVertical: verticalScale(10),
    marginHorizontal: scale(16),
    borderRadius: verticalScale(10),
    elevation: 2,
  },
  sectionTitle: {
    backgroundColor: '#003366',
    color: 'white',
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(20),
    borderRadius: verticalScale(10),
    marginTop: verticalScale(10),
    alignSelf: 'flex-start',
    elevation: 3,
    fontSize: scale(14),
  },
  input: {
    borderWidth: scale(1),
    borderColor: '#ccc',
    borderRadius: scale(6),
    padding: moderateScale(6),
    width: '22%',
    marginHorizontal: scale(8),
  },
  input2: {
    borderWidth: scale(1),
    borderColor: '#ccc',
    borderRadius: scale(6),
    padding: moderateScale(6),
    width: '20%',
    marginHorizontal: scale(6),
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: verticalScale(4),
  },
  row2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(4),
  },
  row3: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(4),
  },
  row4: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(4),
    justifyContent: 'space-between',
  },
  callBtn: {
  backgroundColor: '#003366',
  paddingVertical: verticalScale(8),
  paddingHorizontal: scale(16),
  borderRadius: scale(8),
  justifyContent: 'center',
  alignItems: 'center',
  flex: 1,
  marginHorizontal: moderateScale(40),
  marginVertical: verticalScale(2),
  elevation: 3,
  minHeight: verticalScale(45),
},

callText: {
  color: 'white',
  fontWeight: '600',
  fontSize: scale(13),
  textAlign: 'center',
},
row4: {
  flexDirection: 'row',
  alignItems: 'center',
  marginTop: verticalScale(4),
  justifyContent: 'space-between',
  flexWrap: 'wrap', // Add this
},

});

export default styles;
